### ISSUE TITLE
OPEN CHANNEL button doesn't work

### ISSUE THREAD

**Issue by ivanistheone** [fle-internal/sushibar#27]
<img width="506" alt="screen shot 2017-11-26 at 12 39 15 pm" src="https://user-images.githubusercontent.com/163966/33242702-eaf1af0c-d2a6-11e7-8aae-b4022f910a8d.png">

Expected: open studio in new window

Actual: nothing happens

**Comment by jayoshih** [comment]
Fixed: https://github.com/fle-internal/sushibar/pull/28

**Comment by ivanistheone** [comment]
deployed and tested #28.
